import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { useSelector } from 'react-redux';
import { toast } from 'react-hot-toast';
import api from '../../../api/axios';
import '../../../styles/AdminDailyChallenges.css';

const EXPECTED_DIFFICULTY_BY_WEEKDAY = {
    0: 'Hard',
    1: 'Easy',
    2: 'Easy',
    3: 'Medium',
    4: 'Medium',
    5: 'Hard',
    6: 'Hard'
};

const toUtcDateKey = (value = new Date()) => {
    const date = new Date(value);
    if (Number.isNaN(date.getTime())) return '';
    const year = date.getUTCFullYear();
    const month = String(date.getUTCMonth() + 1).padStart(2, '0');
    const day = String(date.getUTCDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
};

const getExpectedDifficultyForDate = (dateKey) => {
    if (!dateKey) return 'Easy';
    const date = new Date(`${dateKey}T00:00:00.000Z`);
    if (Number.isNaN(date.getTime())) return 'Easy';
    return EXPECTED_DIFFICULTY_BY_WEEKDAY[date.getUTCDay()] || 'Easy';
};

const getDifficultyClass = (difficulty) => {
    if (difficulty === 'Easy') return 'dc-difficulty-easy';
    if (difficulty === 'Medium') return 'dc-difficulty-medium';
    return 'dc-difficulty-hard';
};

const toSourceLabel = (source) => (source === 'ADMIN' ? 'Admin' : 'System Generated');

const DailyChallengesManager = () => {
    const { user } = useSelector((state) => state.auth);
    const isSuperAdmin = user?.role === 'SUPER_ADMIN';

    const [loading, setLoading] = useState(true);
    const [saving, setSaving] = useState(false);
    const [historyLoading, setHistoryLoading] = useState(false);
    const [upcomingLoading, setUpcomingLoading] = useState(false);

    const [history, setHistory] = useState([]);
    const [historyPagination, setHistoryPagination] = useState({ page: 1, pages: 1, total: 0, limit: 50 });

    const [upcoming, setUpcoming] = useState([]);
    const [weeklyPattern, setWeeklyPattern] = useState([]);
    const [insights, setInsights] = useState({
        difficultyDistributionLast30Days: { Easy: 0, Medium: 0, Hard: 0 },
        unscheduledDatesBeforeAutoGeneration: [],
        unscheduledDates: [],
        problemsUsedInLast7Days: [],
        upcomingAutoGeneratedChallenges: []
    });

    const [problems, setProblems] = useState([]);
    const [editingChallengeId, setEditingChallengeId] = useState(null);
    const [form, setForm] = useState({
        date: toUtcDateKey(new Date()),
        problemId: '',
        notes: '',
        replaceExisting: true,
        overrideRepeatedProblem: false,
        overrideDifficultyPattern: false
    });

    const selectedProblem = useMemo(
        () => problems.find((problem) => String(problem._id) === String(form.problemId)) || null,
        [form.problemId, problems]
    );
    const expectedDifficulty = useMemo(
        () => getExpectedDifficultyForDate(form.date),
        [form.date]
    );

    const recentlyUsedProblemIds = useMemo(() => (
        new Set((insights?.problemsUsedInLast7Days || []).map((entry) => String(entry.problemId || '')))
    ), [insights?.problemsUsedInLast7Days]);

    const selectedProblemUsedRecently = Boolean(selectedProblem?._id && recentlyUsedProblemIds.has(String(selectedProblem._id)));
    const selectedDifficultyMismatch = Boolean(selectedProblem?.difficulty && selectedProblem.difficulty !== expectedDifficulty);

    const upcomingMap = useMemo(() => {
        const map = new Map();
        (upcoming || []).forEach((entry) => {
            if (entry?.dateKey) map.set(entry.dateKey, entry);
        });
        return map;
    }, [upcoming]);

    const calendarCells = useMemo(() => {
        const start = new Date(`${toUtcDateKey(new Date())}T00:00:00.000Z`);
        const firstDay = new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth(), 1));
        const lastDay = new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth() + 1, 0));
        const firstWeekday = firstDay.getUTCDay();
        const cells = [];

        for (let i = 0; i < firstWeekday; i += 1) {
            cells.push(null);
        }

        for (let day = 1; day <= lastDay.getUTCDate(); day += 1) {
            const date = new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth(), day));
            const dateKey = toUtcDateKey(date);
            cells.push({
                date,
                dateKey,
                challenge: upcomingMap.get(dateKey) || null
            });
        }
        return cells;
    }, [upcomingMap]);

    const loadHistory = useCallback(async ({ silent = false } = {}) => {
        if (!silent) setHistoryLoading(true);
        try {
            const { data } = await api.get('/admin/daily-challenges/history', {
                params: { days: 180, page: 1, limit: 100 }
            });
            setHistory(Array.isArray(data.history) ? data.history : []);
            setHistoryPagination(data.pagination || { page: 1, pages: 1, total: 0, limit: 100 });
        } catch (error) {
            toast.error(error.response?.data?.message || 'Failed to load daily challenge history');
        } finally {
            if (!silent) setHistoryLoading(false);
        }
    }, []);

    const loadUpcoming = useCallback(async ({ silent = false } = {}) => {
        if (!silent) setUpcomingLoading(true);
        try {
            const { data } = await api.get('/admin/daily-challenges/upcoming', {
                params: { days: 35 }
            });
            setUpcoming(Array.isArray(data.upcoming) ? data.upcoming : []);
            setWeeklyPattern(Array.isArray(data.weeklyPattern) ? data.weeklyPattern : []);
            setInsights(data.insights || {
                difficultyDistributionLast30Days: { Easy: 0, Medium: 0, Hard: 0 },
                unscheduledDatesBeforeAutoGeneration: [],
                unscheduledDates: [],
                problemsUsedInLast7Days: [],
                upcomingAutoGeneratedChallenges: []
            });
        } catch (error) {
            toast.error(error.response?.data?.message || 'Failed to load upcoming daily challenges');
        } finally {
            if (!silent) setUpcomingLoading(false);
        }
    }, []);

    const loadProblems = useCallback(async () => {
        const { data } = await api.get('/problems/admin-list');
        const all = Array.isArray(data?.problems) ? data.problems : [];
        const published = all.filter((problem) => (
            problem?.isPublished === true
            || String(problem?.status || '').toLowerCase() === 'published'
            || String(problem?.status || '').toUpperCase() === 'PUBLISHED'
        ));
        published.sort((a, b) => String(a.title || '').localeCompare(String(b.title || '')));
        setProblems(published);
    }, []);

    const refreshAll = useCallback(async () => {
        setLoading(true);
        try {
            await Promise.all([
                loadProblems(),
                loadHistory({ silent: true }),
                loadUpcoming({ silent: true })
            ]);
        } catch (_) {
            // handled in local loaders
        } finally {
            setLoading(false);
            setHistoryLoading(false);
            setUpcomingLoading(false);
        }
    }, [loadHistory, loadProblems, loadUpcoming]);

    useEffect(() => {
        refreshAll();
    }, [refreshAll]);

    const resetForm = () => {
        setEditingChallengeId(null);
        setForm((prev) => ({
            date: prev.date || toUtcDateKey(new Date()),
            problemId: '',
            notes: '',
            replaceExisting: true,
            overrideRepeatedProblem: false,
            overrideDifficultyPattern: false
        }));
    };

    const onFormChange = (key, value) => {
        setForm((prev) => ({ ...prev, [key]: value }));
    };

    const onPickRandom = () => {
        const expected = getExpectedDifficultyForDate(form.date);
        const notUsed = problems.filter((problem) => !recentlyUsedProblemIds.has(String(problem._id)));
        const preferred = notUsed.filter((problem) => problem.difficulty === expected);
        const pool = preferred.length > 0
            ? preferred
            : (notUsed.length > 0 ? notUsed : problems);

        if (!pool.length) {
            toast.error('No published problems available to pick');
            return;
        }

        const selected = pool[Math.floor(Math.random() * pool.length)];
        setForm((prev) => ({ ...prev, problemId: String(selected._id) }));
        toast.success(`Random pick: ${selected.title}`);
    };

    const handleScheduleSubmit = async (event) => {
        event.preventDefault();
        if (!form.date) {
            toast.error('Please select a challenge date');
            return;
        }
        if (!form.problemId) {
            toast.error('Please select a problem');
            return;
        }

        const payload = {
            date: form.date,
            problemId: form.problemId,
            notes: form.notes,
            replaceExisting: Boolean(form.replaceExisting),
            overrideRepeatedProblem: Boolean(form.overrideRepeatedProblem),
            overrideDifficultyPattern: Boolean(form.overrideDifficultyPattern)
        };

        try {
            setSaving(true);
            if (editingChallengeId) {
                await api.put('/admin/daily-challenges/update', {
                    challengeId: editingChallengeId,
                    ...payload
                });
                toast.success('Daily challenge updated');
            } else {
                await api.post('/admin/daily-challenges/schedule', payload);
                toast.success('Daily challenge scheduled');
            }

            await Promise.all([
                loadHistory({ silent: true }),
                loadUpcoming({ silent: true })
            ]);
            resetForm();
        } catch (error) {
            const serverMessage = error.response?.data?.message || 'Failed to save daily challenge';
            const warnings = error.response?.data?.warnings;
            if (warnings?.repeatedProblem || warnings?.difficultyMismatch) {
                const repeatText = warnings.repeatedProblem ? 'Problem was used in last 7 days.' : '';
                const difficultyText = warnings.difficultyMismatch ? `Expected ${warnings.expectedDifficulty} for ${warnings.weekday}.` : '';
                toast.error(`${serverMessage} ${repeatText} ${difficultyText}`.trim());
            } else {
                toast.error(serverMessage);
            }
        } finally {
            setSaving(false);
        }
    };

    const onEdit = (challenge, replaceOnly = false) => {
        setEditingChallengeId(challenge._id);
        setForm({
            date: challenge.dateKey || challenge.date,
            problemId: replaceOnly ? '' : String(challenge.problemId || challenge.problem?._id || ''),
            notes: challenge.notes || '',
            replaceExisting: true,
            overrideRepeatedProblem: Boolean(challenge.overrideRepeatedProblem),
            overrideDifficultyPattern: Boolean(challenge.overrideDifficultyPattern)
        });
        window.scrollTo({ top: 0, behavior: 'smooth' });
    };

    const onDelete = async (challenge) => {
        const ok = window.confirm(`Delete daily challenge for ${challenge.date}?`);
        if (!ok) return;

        try {
            await api.delete('/admin/daily-challenges/delete', {
                data: {
                    challengeId: challenge._id,
                    date: challenge.date
                }
            });
            toast.success('Daily challenge deleted');
            await Promise.all([
                loadHistory({ silent: true }),
                loadUpcoming({ silent: true })
            ]);
            if (editingChallengeId && String(editingChallengeId) === String(challenge._id)) {
                resetForm();
            }
        } catch (error) {
            toast.error(error.response?.data?.message || 'Failed to delete daily challenge');
        }
    };

    if (loading) {
        return <div className="glass-panel">Loading daily challenge manager...</div>;
    }

    return (
        <div className="dc-admin-page">
            <section className="glass-panel dc-scheduler-panel">
                <div className="dc-panel-head">
                    <div>
                        <h2>Daily Challenge Scheduler</h2>
                        <p>Pick a published problem or let the system keep unscheduled dates random.</p>
                    </div>
                    <div className="dc-head-actions">
                        <Link to="/admin/create-problem" className="btn-secondary">
                            Create New Problem
                        </Link>
                        {editingChallengeId && (
                            <button type="button" className="btn-secondary" onClick={resetForm}>
                                Cancel Edit
                            </button>
                        )}
                    </div>
                </div>

                <form className="dc-form-grid" onSubmit={handleScheduleSubmit}>
                    <label className="form-group">
                        <span className="form-label">Challenge Date</span>
                        <input
                            type="date"
                            className="form-input"
                            value={form.date}
                            onChange={(event) => onFormChange('date', event.target.value)}
                            required
                        />
                        <small className="dc-help-text">
                            Expected difficulty for this date: <strong>{expectedDifficulty}</strong>
                        </small>
                    </label>

                    <label className="form-group">
                        <span className="form-label">Problem</span>
                        <select
                            className="form-select"
                            value={form.problemId}
                            onChange={(event) => onFormChange('problemId', event.target.value)}
                            required
                        >
                            <option value="">Select published problem</option>
                            {problems.map((problem) => (
                                <option key={problem._id} value={problem._id}>
                                    {problem.title} ({problem.difficulty})
                                </option>
                            ))}
                        </select>
                    </label>

                    <label className="form-group">
                        <span className="form-label">Notes (Optional)</span>
                        <input
                            type="text"
                            className="form-input"
                            value={form.notes}
                            onChange={(event) => onFormChange('notes', event.target.value)}
                            placeholder="Reason or context"
                        />
                    </label>

                    <div className="dc-switch-grid">
                        <label className="dc-switch-item">
                            <input
                                type="checkbox"
                                checked={Boolean(form.replaceExisting)}
                                onChange={(event) => onFormChange('replaceExisting', event.target.checked)}
                            />
                            <span>Replace existing challenge if date already has one</span>
                        </label>
                        <label className="dc-switch-item">
                            <input
                                type="checkbox"
                                checked={Boolean(form.overrideRepeatedProblem)}
                                onChange={(event) => onFormChange('overrideRepeatedProblem', event.target.checked)}
                            />
                            <span>Allow repeated problem (used in last 7 days)</span>
                        </label>
                        <label className="dc-switch-item">
                            <input
                                type="checkbox"
                                checked={Boolean(form.overrideDifficultyPattern)}
                                onChange={(event) => onFormChange('overrideDifficultyPattern', event.target.checked)}
                            />
                            <span>Allow difficulty mismatch with weekly pattern</span>
                        </label>
                    </div>

                    {(selectedProblemUsedRecently || selectedDifficultyMismatch) && (
                        <div className="dc-warning-box">
                            {selectedProblemUsedRecently && (
                                <div>Warning: selected problem was used in last 7 days.</div>
                            )}
                            {selectedDifficultyMismatch && (
                                <div>
                                    Warning: expected <strong>{expectedDifficulty}</strong> for {form.date}, selected <strong>{selectedProblem?.difficulty}</strong>.
                                </div>
                            )}
                        </div>
                    )}

                    <div className="dc-form-actions">
                        {isSuperAdmin && (
                            <button type="button" className="btn-secondary" onClick={onPickRandom}>
                                Generate Random Problem
                            </button>
                        )}
                        <button type="submit" className="btn-primary" disabled={saving}>
                            {saving ? 'Saving...' : (editingChallengeId ? 'Update Challenge' : 'Schedule Challenge')}
                        </button>
                    </div>
                </form>
            </section>

            <section className="glass-panel dc-pattern-panel">
                <div className="dc-panel-head">
                    <div>
                        <h3>Weekly Difficulty Pattern</h3>
                        <p>Pattern: Easy, Easy, Medium, Medium, Hard, Hard, Hard</p>
                    </div>
                    {upcomingLoading && <span className="dc-loading-inline">Refreshing...</span>}
                </div>
                <div className="dc-pattern-grid">
                    {weeklyPattern.map((entry) => (
                        <div key={entry.day} className="dc-pattern-card">
                            <div className="dc-pattern-day">{entry.day}</div>
                            <div className={`dc-difficulty-pill ${getDifficultyClass(entry.expectedDifficulty)}`}>
                                {entry.expectedDifficulty}
                            </div>
                            <div className="dc-pattern-meta">
                                {entry.date ? `Next: ${entry.date}` : 'Date unavailable'}
                            </div>
                            <div className="dc-pattern-meta">
                                {entry.scheduled ? `Scheduled (${entry.scheduledSource})` : 'Not scheduled'}
                            </div>
                        </div>
                    ))}
                </div>
            </section>

            <section className="glass-panel dc-insights-panel">
                <h3>Smart Insights</h3>
                <div className="dc-insights-grid">
                    <div className="dc-insight-card">
                        <h4>Difficulty Distribution (Last 30 Days)</h4>
                        <ul>
                            <li><span className="dc-dot easy" /> Easy: {insights?.difficultyDistributionLast30Days?.Easy || 0}</li>
                            <li><span className="dc-dot medium" /> Medium: {insights?.difficultyDistributionLast30Days?.Medium || 0}</li>
                            <li><span className="dc-dot hard" /> Hard: {insights?.difficultyDistributionLast30Days?.Hard || 0}</li>
                        </ul>
                    </div>

                    <div className="dc-insight-card">
                        <h4>Upcoming Unscheduled Dates</h4>
                        {Array.isArray(insights?.unscheduledDates) && insights.unscheduledDates.length > 0 ? (
                            <div className="dc-chip-wrap">
                                {insights.unscheduledDates.map((dateKey) => (
                                    <span key={dateKey} className="dc-chip">{dateKey}</span>
                                ))}
                            </div>
                        ) : (
                            <p>None. Upcoming dates are covered.</p>
                        )}
                    </div>

                    <div className="dc-insight-card">
                        <h4>Problems Used in Last 7 Days</h4>
                        {Array.isArray(insights?.problemsUsedInLast7Days) && insights.problemsUsedInLast7Days.length > 0 ? (
                            <ul className="dc-recent-list">
                                {insights.problemsUsedInLast7Days.slice(0, 8).map((entry) => (
                                    <li key={`${entry.date}-${entry.problemId}`}>
                                        <span>{entry.date}</span>
                                        <span>{entry.title}</span>
                                        <span className={`dc-difficulty-pill ${getDifficultyClass(entry.difficulty)}`}>{entry.difficulty}</span>
                                    </li>
                                ))}
                            </ul>
                        ) : (
                            <p>No challenge usage in last 7 days.</p>
                        )}
                    </div>

                    <div className="dc-insight-card">
                        <h4>Upcoming Auto-Generated Challenges</h4>
                        <p>{Array.isArray(insights?.upcomingAutoGeneratedChallenges) ? insights.upcomingAutoGeneratedChallenges.length : 0}</p>
                    </div>
                </div>
            </section>

            <section className="glass-panel dc-history-panel">
                <div className="dc-panel-head">
                    <div>
                        <h3>Daily Challenge History</h3>
                        <p>Total rows: {historyPagination.total || history.length}</p>
                    </div>
                    {historyLoading && <span className="dc-loading-inline">Refreshing...</span>}
                </div>
                <div className="table-container">
                    <table className="data-table">
                        <thead>
                            <tr>
                                <th>Date</th>
                                <th>Problem Title</th>
                                <th>Difficulty</th>
                                <th>Source</th>
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {history.length === 0 && (
                                <tr>
                                    <td colSpan={6} className="admin-empty-row">No daily challenges found.</td>
                                </tr>
                            )}
                            {history.map((entry) => (
                                <tr key={entry._id}>
                                    <td>{entry.date}</td>
                                    <td>{entry.problem?.title || 'Unknown problem'}</td>
                                    <td>
                                        <span className={`dc-difficulty-pill ${getDifficultyClass(entry.difficulty)}`}>
                                            {entry.difficulty}
                                        </span>
                                    </td>
                                    <td>{toSourceLabel(entry.source)}</td>
                                    <td>{entry.status}</td>
                                    <td>
                                        <div className="dc-row-actions">
                                            <button type="button" className="btn-secondary" onClick={() => onEdit(entry, false)}>Edit</button>
                                            <button type="button" className="btn-secondary" onClick={() => onEdit(entry, true)}>Replace</button>
                                            <button type="button" className="btn-secondary dc-danger-btn" onClick={() => onDelete(entry)}>Delete</button>
                                        </div>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </section>

            <section className="glass-panel dc-calendar-panel">
                <div className="dc-panel-head">
                    <div>
                        <h3>Calendar View</h3>
                        <p>Upcoming challenges for the current month</p>
                    </div>
                </div>
                <div className="dc-calendar-grid">
                    {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((day) => (
                        <div key={day} className="dc-calendar-weekday">{day}</div>
                    ))}
                    {calendarCells.map((cell, index) => {
                        if (!cell) {
                            return <div key={`blank-${index}`} className="dc-calendar-cell blank" />;
                        }
                        const challenge = cell.challenge;
                        return (
                            <div key={cell.dateKey} className={`dc-calendar-cell ${challenge ? 'filled' : 'empty'}`}>
                                <div className="dc-cell-date">{cell.date.getUTCDate()}</div>
                                {challenge ? (
                                    <>
                                        <div className="dc-cell-title">{challenge.problem?.title || 'Unknown'}</div>
                                        <div className={`dc-difficulty-pill ${getDifficultyClass(challenge.difficulty)}`}>
                                            {challenge.difficulty}
                                        </div>
                                        <div className="dc-cell-source">{toSourceLabel(challenge.source)}</div>
                                    </>
                                ) : (
                                    <div className="dc-cell-empty">No challenge</div>
                                )}
                            </div>
                        );
                    })}
                </div>
            </section>
        </div>
    );
};

export default DailyChallengesManager;
